<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mac-mini-DuniceEdCast.local" failures="12" tests="12" name="WrongLoginTest" time="4.576" errors="0" timestamp="2021-12-27T16:47:06 MSK" skipped="0">
  <testcase classname="WrongLoginTest" name="emptyEmail" time="0.228">
    <failure message="
Multiple Failures (3 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (3 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.emptyEmail(WrongLoginTest.java:164)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- emptyEmail -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="incorrectEmail1" time="0.214">
    <failure message="
Multiple Failures (6 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8, 9]&gt;
but could not find the following element(s):
 &lt;[8, 9]&gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[9]&gt;
but could not find the following element(s):
 &lt;[9]&gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (6 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- incorrectEmail1 -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="incorrectEmail4" time="0.225">
    <failure message="
Multiple Failures (9 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8, 9]&gt;
but could not find the following element(s):
 &lt;[8, 9]&gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[9]&gt;
but could not find the following element(s):
 &lt;[9]&gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (9 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- incorrectEmail4 -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="withoutEmailAndPassword" time="0.211">
    <failure message="
Multiple Failures (11 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8, 9]&gt;
but could not find the following element(s):
 &lt;[8, 9]&gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[9]&gt;
but could not find the following element(s):
 &lt;[9]&gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)
-- failure 11 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[8, 26]&gt;
but could not find the following element(s):
 &lt;[8, 26]&gt;

at WrongLoginTest.withoutEmailAndPassword(WrongLoginTest.java:259)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (11 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)
-- failure 11 --
Expecting ArrayList:
 <[5]>
to contain:
 <[8, 26]>
but could not find the following element(s):
 <[8, 26]>

at WrongLoginTest.withoutEmailAndPassword(WrongLoginTest.java:259)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.withoutEmailAndPassword(WrongLoginTest.java:261)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- withoutEmailAndPassword -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="incorrectEmail3" time="0.294">
    <failure message="
Multiple Failures (8 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8, 9]&gt;
but could not find the following element(s):
 &lt;[8, 9]&gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[9]&gt;
but could not find the following element(s):
 &lt;[9]&gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (8 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- incorrectEmail3 -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="WithoutEmail" time="1.977">
    <failure message="
Multiple Failures (1 failure)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.WithoutEmail(WrongLoginTest.java:242)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- WithoutEmail -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="incorrectEmail2" time="0.251">
    <failure message="
Multiple Failures (7 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8, 9]&gt;
but could not find the following element(s):
 &lt;[8, 9]&gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[9]&gt;
but could not find the following element(s):
 &lt;[9]&gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (7 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- incorrectEmail2 -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="emptyPassword" time="0.215">
    <failure message="
Multiple Failures (5 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8, 9]&gt;
but could not find the following element(s):
 &lt;[8, 9]&gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[9]&gt;
but could not find the following element(s):
 &lt;[9]&gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (5 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.emptyPassword(WrongLoginTest.java:184)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- emptyPassword -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="correctEmailWithoutPassword" time="0.288">
    <failure message="
Multiple Failures (2 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (2 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:223)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- correctEmailWithoutPassword -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="emptyEmailAndPassword" time="0.254">
    <failure message="
Multiple Failures (4 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8, 9]&gt;
but could not find the following element(s):
 &lt;[8, 9]&gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (4 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:204)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- emptyEmailAndPassword -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="incorrectEmail5" time="0.200">
    <failure message="
Multiple Failures (10 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8, 9]&gt;
but could not find the following element(s):
 &lt;[8, 9]&gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[9]&gt;
but could not find the following element(s):
 &lt;[9]&gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (10 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:124)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- incorrectEmail5 -->
  <system-out/>
  <testcase classname="WrongLoginTest" name="userDoesNotExist" time="0.219">
    <failure message="
Multiple Failures (10 failures)
-- failure 1 --
Expecting ArrayList:
 &lt;[4]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[26]&gt;
but could not find the following element(s):
 &lt;[26]&gt;

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8]&gt;
but could not find the following element(s):
 &lt;[8]&gt;

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 &lt;[3]&gt;
to contain:
 &lt;[8, 9]&gt;
but could not find the following element(s):
 &lt;[8, 9]&gt;

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[9]&gt;
but could not find the following element(s):
 &lt;[9]&gt;

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 &lt;[0]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 &lt;[5]&gt;
to contain:
 &lt;[17]&gt;
but could not find the following element(s):
 &lt;[17]&gt;

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)" type="org.assertj.core.error.AssertJMultipleFailuresError">
      <![CDATA[org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (10 failures)
-- failure 1 --
Expecting ArrayList:
 <[4]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.WithoutEmail(WrongLoginTest.java:240)
-- failure 2 --
Expecting ArrayList:
 <[5]>
to contain:
 <[26]>
but could not find the following element(s):
 <[26]>

at WrongLoginTest.correctEmailWithoutPassword(WrongLoginTest.java:221)
-- failure 3 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8]>
but could not find the following element(s):
 <[8]>

at WrongLoginTest.emptyEmail(WrongLoginTest.java:163)
-- failure 4 --
Expecting ArrayList:
 <[3]>
to contain:
 <[8, 9]>
but could not find the following element(s):
 <[8, 9]>

at WrongLoginTest.emptyEmailAndPassword(WrongLoginTest.java:202)
-- failure 5 --
Expecting ArrayList:
 <[5]>
to contain:
 <[9]>
but could not find the following element(s):
 <[9]>

at WrongLoginTest.emptyPassword(WrongLoginTest.java:183)
-- failure 6 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail1(WrongLoginTest.java:40)
-- failure 7 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail2(WrongLoginTest.java:59)
-- failure 8 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail3(WrongLoginTest.java:80)
-- failure 9 --
Expecting ArrayList:
 <[0]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail4(WrongLoginTest.java:102)
-- failure 10 --
Expecting ArrayList:
 <[5]>
to contain:
 <[17]>
but could not find the following element(s):
 <[17]>

at WrongLoginTest.incorrectEmail5(WrongLoginTest.java:123)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at WrongLoginTest.userDoesNotExist(WrongLoginTest.java:144)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- userDoesNotExist -->
  <system-out/>
</testsuite> <!-- WrongLoginTest -->
